#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "jkuyumcu/06235647@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
DROP TABLE ASSIGN_AGE_RATING;
DROP TABLE CREATES_CUSTOMER;
DROP TABLE MOVIE_HAS_GENRE;
DROP TABLE PURCHASE_MOVIE;
DROP TABLE PURCHASES_SUBSCRIPTION;
DROP TABLE REVIEW;
DROP TABLE SUBSCRIPTION_RATE;
DROP TABLE UPDATE_CATALOGUE;
DROP TABLE USER_ACCOUNT;
DROP TABLE ADMIN_ACCOUNT;
DROP TABLE AGE_RATING;
DROP TABLE CUSTOMER;
DROP TABLE GENRE;
DROP TABLE MOVIE;
exit;
EOF
